import { TroubleshootingScenario } from '@netvision/shared';

export const TROUBLESHOOTING_SCENARIOS: TroubleshootingScenario[] = [
  // 1. DNS Resolution Failure
  {
    id: 'scen-dns-fail',
    slug: 'dns-resolution-failure',
    title: 'DNS Resolution Failure: Internal Connectivity Active, Hostnames Unresolvable',
    incidentDescription:
      'Engineers at Branch Office Alpha report that while internal direct IP services are functioning, web browsing to internet domains (e.g. portal.netvision.io) fails with "Server Not Found" and DNS timeouts.',
    category: 'Core IP Services',
    difficulty: 'BEGINNER',
    estimatedMinutes: 15,
    networkingConcepts: ['DNS (Domain Name System)', 'UDP Port 53', 'Layer 7 Application Protocol', 'Resolver Configuration'],
    initialSymptoms: [
      'Users cannot resolve public domain names like portal.netvision.io or cdn.netvision.io',
      'Direct IP ping to 8.8.8.8 and default gateway 192.168.1.1 succeeds',
      'Web browser displays ERR_NAME_NOT_RESOLVED on client workstations',
    ],
    topology: {
      nodes: [
        {
          id: 'node-pc1',
          name: 'Workstation-01',
          type: 'pc',
          ipAddress: '192.168.1.50',
          subnetMask: '255.255.255.0',
          defaultGateway: '192.168.1.1',
          dnsServers: ['192.168.1.250'],
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-sw1',
          name: 'Access-Switch-01',
          type: 'switch',
          status: 'online',
          position: { x: 380, y: 220 },
        },
        {
          id: 'node-gw1',
          name: 'Edge-Router-01',
          type: 'router',
          ipAddress: '192.168.1.1',
          subnetMask: '255.255.255.0',
          status: 'online',
          position: { x: 620, y: 220 },
        },
        {
          id: 'node-dns-pub',
          name: 'Public-DNS (1.1.1.1)',
          type: 'server',
          ipAddress: '1.1.1.1',
          status: 'online',
          position: { x: 880, y: 150 },
        },
      ],
      links: [
        { id: 'link-1', sourceNodeId: 'node-pc1', targetNodeId: 'node-sw1', status: 'connected', latencyMs: 1 },
        { id: 'link-2', sourceNodeId: 'node-sw1', targetNodeId: 'node-gw1', status: 'connected', latencyMs: 1 },
        { id: 'link-3', sourceNodeId: 'node-gw1', targetNodeId: 'node-dns-pub', status: 'connected', latencyMs: 12 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-dns-1',
        title: 'Workstation IP Configuration',
        category: 'CONFIG',
        description: 'Output from ipconfig /all shows DNS server set to nonexistent IP 192.168.1.250',
        data: 'DNS Servers . . . . . . . . . . . : 192.168.1.250 (Non-responsive decommissioning remnant)',
        discoveredByCommand: 'ipconfig /all',
        isUnlocked: false,
      },
      {
        id: 'ev-dns-2',
        title: 'DNS Query Timeout Telemetry',
        category: 'LOG',
        description: 'nslookup queries to 192.168.1.250 on UDP port 53 timed out after 2000ms',
        data: 'DNS request timed out.\n    timeout was 2 seconds.\n*** Can\'t find server name for address 192.168.1.250: Timed out',
        discoveredByCommand: 'nslookup portal.netvision.io',
        isUnlocked: false,
      },
      {
        id: 'ev-dns-3',
        title: 'External DNS Reachability Test',
        category: 'CLI_OUTPUT',
        description: 'Direct DNS query to Cloudflare public resolver 1.1.1.1 succeeds immediately',
        data: 'Server: 1.1.1.1\nAddress: 1.1.1.1#53\nNon-authoritative answer:\nName: portal.netvision.io\nAddress: 104.21.48.12',
        discoveredByCommand: 'nslookup portal.netvision.io 1.1.1.1',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ipconfig /all',
        description: 'Display network adapter configuration and configured DNS resolvers',
        category: 'DIAGNOSTIC',
        brokenOutput: `Ethernet adapter Local Area Connection:\n  IPv4 Address. . . . . . . . . . . : 192.168.1.50\n  Subnet Mask . . . . . . . . . . . : 255.255.255.0\n  Default Gateway . . . . . . . . . : 192.168.1.1\n  DNS Servers . . . . . . . . . . . : 192.168.1.250`,
        fixedOutput: `Ethernet adapter Local Area Connection:\n  IPv4 Address. . . . . . . . . . . : 192.168.1.50\n  Subnet Mask . . . . . . . . . . . : 255.255.255.0\n  Default Gateway . . . . . . . . . : 192.168.1.1\n  DNS Servers . . . . . . . . . . . : 1.1.1.1\n                                      8.8.8.8`,
        unlocksEvidenceId: 'ev-dns-1',
      },
      {
        command: 'ping 192.168.1.1',
        description: 'Test ICMP reachability to local gateway router',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 192.168.1.1: 56 data bytes\n64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=0.82 ms\n64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.79 ms\n--- 192.168.1.1 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss`,
        fixedOutput: `PING 192.168.1.1: 56 data bytes\n64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=0.82 ms\n--- 192.168.1.1 ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss`,
      },
      {
        command: 'ping 8.8.8.8',
        description: 'Test ICMP reachability to internet IP address',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 8.8.8.8: 56 data bytes\n64 bytes from 8.8.8.8: icmp_seq=0 ttl=118 time=14.2 ms\n64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=13.9 ms\n--- 8.8.8.8 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss`,
        fixedOutput: `PING 8.8.8.8: 56 data bytes\n64 bytes from 8.8.8.8: icmp_seq=0 ttl=118 time=14.2 ms\n--- 8.8.8.8 ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss`,
      },
      {
        command: 'nslookup portal.netvision.io',
        description: 'Query configured DNS server for portal.netvision.io hostname',
        category: 'DIAGNOSTIC',
        brokenOutput: `Server:  192.168.1.250\nAddress: 192.168.1.250#53\n\n*** Request to 192.168.1.250 timed-out after 2000ms.\n*** Can't find portal.netvision.io: No response from server`,
        fixedOutput: `Server:  1.1.1.1\nAddress: 1.1.1.1#53\n\nNon-authoritative answer:\nName:    portal.netvision.io\nAddress: 104.21.48.12`,
        unlocksEvidenceId: 'ev-dns-2',
      },
      {
        command: 'nslookup portal.netvision.io 1.1.1.1',
        description: 'Explicitly query Cloudflare public DNS server 1.1.1.1',
        category: 'DIAGNOSTIC',
        brokenOutput: `Server:  1.1.1.1\nAddress: 1.1.1.1#53\n\nNon-authoritative answer:\nName:    portal.netvision.io\nAddress: 104.21.48.12`,
        fixedOutput: `Server:  1.1.1.1\nAddress: 1.1.1.1#53\n\nNon-authoritative answer:\nName:    portal.netvision.io\nAddress: 104.21.48.12`,
        unlocksEvidenceId: 'ev-dns-3',
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-dns-1',
        description: 'The workstation is configured with a dead/decommissioned DNS resolver IP (192.168.1.250) that does not reply on UDP port 53.',
        isCorrect: true,
        explanation: 'Local Layer 2/3 connectivity and gateway routing are intact, but name resolution fails because 192.168.1.250 is unreachable or no longer operating as a recursive resolver.',
      },
      {
        id: 'rc-dns-2',
        description: 'The default gateway 192.168.1.1 is dropping all outbound internet traffic.',
        isCorrect: false,
        explanation: 'Incorrect: Pings to 8.8.8.8 and nslookup directly to 1.1.1.1 both succeed through the gateway.',
      },
      {
        id: 'rc-dns-3',
        description: 'The workstation subnet mask is misconfigured.',
        isCorrect: false,
        explanation: 'Incorrect: The workstation can ping its default gateway 192.168.1.1 with 0% packet loss.',
      },
      {
        id: 'rc-dns-4',
        description: 'The domain portal.netvision.io has expired and does not exist in public DNS.',
        isCorrect: false,
        explanation: 'Incorrect: Querying 1.1.1.1 returns a valid A record (104.21.48.12).',
      },
    ],
    hiddenRootCauseId: 'rc-dns-1',
    remediationOptions: [
      {
        id: 'rem-dns-1',
        title: 'Reconfigure DNS Server Addresses to 1.1.1.1 and 8.8.8.8',
        commandSyntax: 'netsh interface ip set dns "Local Area Connection" static 1.1.1.1',
        actionDescription: 'Update workstation adapter DNS server settings to active public resolvers (1.1.1.1 & 8.8.8.8).',
        isCorrect: true,
        explanation: 'Configuring valid upstream DNS resolvers immediately restores name resolution for all applications.',
      },
      {
        id: 'rem-dns-2',
        title: 'Reboot the Default Gateway Router',
        commandSyntax: 'reload',
        actionDescription: 'Trigger a cold restart of Edge-Router-01.',
        isCorrect: false,
        explanation: 'Rebooting the router will cause unnecessary downtime without changing the client DNS IP.',
      },
      {
        id: 'rem-dns-3',
        title: 'Flush ARP cache on Workstation',
        commandSyntax: 'arp -d *',
        actionDescription: 'Clear all cached MAC addresses.',
        isCorrect: false,
        explanation: 'ARP is healthy; the problem is at Layer 7 DNS resolver configuration.',
      },
      {
        id: 'rem-dns-4',
        title: 'Disable Windows Firewall',
        commandSyntax: 'netsh advfirewall set allprofiles state off',
        actionDescription: 'Completely disable host-based firewall.',
        isCorrect: false,
        explanation: 'Disabling firewall is unnecessary and compromises security.',
      },
    ],
    correctRemediationId: 'rem-dns-1',
    verificationTests: [
      {
        id: 'test-dns-1',
        name: 'Validate Primary DNS Resolution',
        testCommand: 'nslookup portal.netvision.io',
        expectedOutputSubstring: '104.21.48.12',
        failureMessage: 'Hostname portal.netvision.io failed to resolve.',
        successMessage: 'portal.netvision.io successfully resolved to 104.21.48.12.',
      },
      {
        id: 'test-dns-2',
        name: 'Validate Secondary Domain Resolution',
        testCommand: 'nslookup cdn.netvision.io',
        expectedOutputSubstring: 'Address:',
        failureMessage: 'Secondary DNS resolution failed.',
        successMessage: 'Secondary DNS resolution operational.',
      },
    ],
    postMortem: {
      summary: 'Host DNS resolver pointed to a decommissioned legacy server IP (192.168.1.250), preventing hostname lookups despite intact IP routing.',
      rootCauseAnalysis: 'During recent data center server migrations, the local DNS forwarder at 192.168.1.250 was retired. Static client IP configurations were not updated to the new DNS IPs, resulting in DNS query timeouts.',
      osiLayer: 'Layer 7 (Application)',
      preventionBestPractices: [
        'Use DHCP Option 6 (Domain Name Server) to dynamically distribute DNS resolvers rather than hardcoding static IPs.',
        'Implement DNS server monitoring and health checks prior to server decommissioning.',
        'Ensure secondary and tertiary DNS resolvers are configured across all subnets.',
      ],
      recommendedCommands: ['ipconfig /all', 'nslookup <host> [server]', 'ipconfig /flushdns', 'dig +trace <domain>'],
    },
  },

  // 2. DHCP Failure
  {
    id: 'scen-dhcp-fail',
    slug: 'dhcp-failure',
    title: 'DHCP Failure: Workstation Assigned APIPA 169.254.x.x Auto-Configuration Address',
    incidentDescription:
      'A newly deployed laptop in Conference Room B is unable to communicate with any LAN or internet devices. Inspection shows it has been assigned IP 169.254.88.102.',
    category: 'Core IP Services',
    difficulty: 'BEGINNER',
    estimatedMinutes: 15,
    networkingConcepts: ['DHCP (Dynamic Host Configuration Protocol)', 'APIPA (RFC 3927)', 'DHCP Relay / IP Helper', 'UDP Broadcast (Ports 67/68)'],
    initialSymptoms: [
      'Client workstation cannot reach any network hosts or internet gateways',
      'Adapter IPv4 address displays 169.254.x.x (APIPA automatic private IP address)',
      'Subnet mask displays 255.255.0.0 with empty default gateway field',
    ],
    topology: {
      nodes: [
        {
          id: 'node-laptop1',
          name: 'Conference-Laptop',
          type: 'pc',
          ipAddress: '169.254.88.102',
          subnetMask: '255.255.0.0',
          defaultGateway: '',
          status: 'offline',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-sw-conf',
          name: 'Conf-Switch-VLAN30',
          type: 'switch',
          status: 'online',
          position: { x: 380, y: 220 },
        },
        {
          id: 'node-rtr-core',
          name: 'Core-Router-VLAN30-SVI',
          type: 'router',
          ipAddress: '192.168.30.1',
          subnetMask: '255.255.255.0',
          status: 'online',
          position: { x: 620, y: 220 },
        },
        {
          id: 'node-dhcp-srv',
          name: 'Enterprise-DHCP-Server',
          type: 'server',
          ipAddress: '10.10.10.50',
          status: 'online',
          position: { x: 880, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-laptop1', targetNodeId: 'node-sw-conf', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-sw-conf', targetNodeId: 'node-rtr-core', status: 'connected', latencyMs: 1 },
        { id: 'l3', sourceNodeId: 'node-rtr-core', targetNodeId: 'node-dhcp-srv', status: 'connected', latencyMs: 2 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-dhcp-1',
        title: 'APIPA Address Allocation on Client',
        category: 'CONFIG',
        description: 'Workstation ipconfig confirms 169.254.88.102 (Automatic Private IP Addressing)',
        data: 'Autoconfiguration IPv4 Address. . : 169.254.88.102\nSubnet Mask . . . . . . . . . . . : 255.255.0.0\nDefault Gateway . . . . . . . . . :',
        discoveredByCommand: 'ipconfig /all',
        isUnlocked: false,
      },
      {
        id: 'ev-dhcp-2',
        title: 'DHCP Discovery Broadcast Dropped at Router',
        category: 'PACKET_TRACE',
        description: 'Client DHCP Discover broadcast 255.255.255.255:67 reaches router VLAN 30 SVI but is dropped because ip helper-address is missing',
        data: 'Router SVI VLAN 30 Interface Config:\ninterface Vlan30\n  ip address 192.168.30.1 255.255.255.0\n  ! No ip helper-address configured for DHCP relay to 10.10.10.50',
        discoveredByCommand: 'show running-config interface vlan 30',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ipconfig /all',
        description: 'Inspect adapter IP configuration',
        category: 'DIAGNOSTIC',
        brokenOutput: `Ethernet adapter Ethernet 1:\n  DHCP Enabled. . . . . . . . . . . : Yes\n  Autoconfiguration Enabled . . . . : Yes\n  Autoconfiguration IPv4 Address. . : 169.254.88.102\n  Subnet Mask . . . . . . . . . . . : 255.255.0.0\n  Default Gateway . . . . . . . . . : \n  DHCP Server . . . . . . . . . . . : `,
        fixedOutput: `Ethernet adapter Ethernet 1:\n  DHCP Enabled. . . . . . . . . . . : Yes\n  IPv4 Address. . . . . . . . . . . : 192.168.30.45\n  Subnet Mask . . . . . . . . . . . : 255.255.255.0\n  Default Gateway . . . . . . . . . : 192.168.30.1\n  DHCP Server . . . . . . . . . . . : 10.10.10.50\n  DNS Servers . . . . . . . . . . . : 1.1.1.1`,
        unlocksEvidenceId: 'ev-dhcp-1',
      },
      {
        command: 'show running-config interface vlan 30',
        description: 'Inspect router VLAN 30 SVI gateway configuration',
        category: 'INSPECTION',
        brokenOutput: `interface Vlan30\n description Conference Room Network\n ip address 192.168.30.1 255.255.255.0\n no shutdown`,
        fixedOutput: `interface Vlan30\n description Conference Room Network\n ip address 192.168.30.1 255.255.255.0\n ip helper-address 10.10.10.50\n no shutdown`,
        unlocksEvidenceId: 'ev-dhcp-2',
      },
      {
        command: 'ipconfig /renew',
        description: 'Request new DHCP lease from network',
        category: 'DIAGNOSTIC',
        brokenOutput: `An error occurred while renewing interface Ethernet 1 : unable to contact your DHCP server. Request has timed out.`,
        fixedOutput: `Connection-specific DNS Suffix  . : netvision.lan\nIPv4 Address. . . . . . . . . . . : 192.168.30.45\nSubnet Mask . . . . . . . . . . . : 255.255.255.0\nDefault Gateway . . . . . . . . . : 192.168.30.1`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-dhcp-1',
        description: 'The router VLAN 30 SVI interface lacks an "ip helper-address" DHCP relay agent pointing to the centralized DHCP server at 10.10.10.50.',
        isCorrect: true,
        explanation: 'DHCP DISCOVER is a Layer 2 broadcast that routers drop by default unless DHCP relay is configured.',
      },
      {
        id: 'rc-dhcp-2',
        description: 'The laptop network interface card hardware is defective.',
        isCorrect: false,
        explanation: 'The NIC successfully initialized APIPA, indicating operating hardware.',
      },
      {
        id: 'rc-dhcp-3',
        description: 'The DHCP server pool on 10.10.10.50 has run out of IP addresses.',
        isCorrect: false,
        explanation: 'The router was dropping DHCP discovery packets before they ever reached the server.',
      },
    ],
    hiddenRootCauseId: 'rc-dhcp-1',
    remediationOptions: [
      {
        id: 'rem-dhcp-1',
        title: 'Configure "ip helper-address 10.10.10.50" on VLAN 30 Interface',
        commandSyntax: 'interface Vlan30\n ip helper-address 10.10.10.50',
        actionDescription: 'Enable DHCP Relay on Router SVI to forward client UDP broadcasts as unicast to the central DHCP server.',
        isCorrect: true,
        explanation: 'This allows DHCP broadcasts from VLAN 30 to reach the DHCP server in the server subnet.',
      },
      {
        id: 'rem-dhcp-2',
        title: 'Set static APIPA address 169.254.1.1 on the router',
        commandSyntax: 'interface Vlan30\n ip address 169.254.1.1 255.255.0.0',
        actionDescription: 'Assign an APIPA IP address to the router.',
        isCorrect: false,
        explanation: 'APIPA is link-local non-routable address space; this violates enterprise addressing.',
      },
    ],
    correctRemediationId: 'rem-dhcp-1',
    verificationTests: [
      {
        id: 'test-dhcp-1',
        name: 'Validate DHCP Lease Acquisition',
        testCommand: 'ipconfig /renew',
        expectedOutputSubstring: '192.168.30.',
        failureMessage: 'DHCP lease renewal failed.',
        successMessage: 'Workstation received valid DHCP lease 192.168.30.45 from 10.10.10.50.',
      },
      {
        id: 'test-dhcp-2',
        name: 'Verify Gateway Ping',
        testCommand: 'ping 192.168.30.1',
        expectedOutputSubstring: '0% packet loss',
        failureMessage: 'Gateway reachability check failed.',
        successMessage: 'Default gateway 192.168.30.1 reachable with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'Clients on newly provisioned VLAN 30 fell back to APIPA (169.254.x.x) because router dropped DHCP broadcasts due to missing ip helper-address relay configuration.',
      rootCauseAnalysis: 'DHCP client discovery uses broadcast 255.255.255.255. Routers terminate broadcast domains and do not forward broadcasts between subnets without an ip helper-address configured.',
      osiLayer: 'Layer 7 (Application)',
      preventionBestPractices: [
        'Include DHCP relay (ip helper-address) in standard switch/router SVI provisioning templates.',
        'Monitor DHCP lease allocation rates and relay agent telemetry.',
      ],
      recommendedCommands: ['ipconfig /renew', 'show ip dhcp binding', 'show running-config interface <int>', 'ip helper-address <ip>'],
    },
  },

  // 3. Incorrect Subnet Mask
  {
    id: 'scen-mask-mismatch',
    slug: 'incorrect-subnet-mask',
    title: 'Incorrect Subnet Mask: Intra-Subnet Works, Inter-Subnet & Gateway Fails',
    incidentDescription:
      'Server-02 (192.168.1.10) can ping adjacent server (192.168.1.20) but cannot communicate with external servers in 192.168.2.0/24 or the internet gateway 192.168.1.1.',
    category: 'IP Addressing & Subnetting',
    difficulty: 'BEGINNER',
    estimatedMinutes: 15,
    networkingConcepts: ['IPv4 Subnet Masking', 'CIDR Notation', 'Local vs Remote Routing Decision', 'Default Gateway Forwarding'],
    initialSymptoms: [
      'Server-02 can ping some local LAN peers, but pings to 192.168.2.50 fail with "Destination host unreachable"',
      'Traffic destined for remote networks is not being forwarded to default gateway 192.168.1.1',
    ],
    topology: {
      nodes: [
        {
          id: 'node-srv2',
          name: 'Server-02',
          type: 'server',
          ipAddress: '192.168.1.10',
          subnetMask: '255.255.0.0', // Mismatch: should be 255.255.255.0
          defaultGateway: '192.168.1.1',
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-gw-rtr',
          name: 'Gateway-Router',
          type: 'router',
          ipAddress: '192.168.1.1',
          subnetMask: '255.255.255.0',
          status: 'online',
          position: { x: 450, y: 220 },
        },
        {
          id: 'node-dest-srv',
          name: 'Remote-Server',
          type: 'server',
          ipAddress: '192.168.2.50',
          subnetMask: '255.255.255.0',
          status: 'online',
          position: { x: 780, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-srv2', targetNodeId: 'node-gw-rtr', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-gw-rtr', targetNodeId: 'node-dest-srv', status: 'connected', latencyMs: 2 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-mask-1',
        title: 'Server-02 Subnet Mask Configuration',
        category: 'CONFIG',
        description: 'Server-02 has subnet mask 255.255.0.0 (/16) instead of standard subnet /24',
        data: 'IPv4 Address: 192.168.1.10\nSubnet Mask: 255.255.0.0\nDefault Gateway: 192.168.1.1',
        discoveredByCommand: 'ip addr show eth0',
        isUnlocked: false,
      },
      {
        id: 'ev-mask-2',
        title: 'ARP Request for Remote IP on Local Wire',
        category: 'PACKET_TRACE',
        description: 'Because Server-02 thinks 192.168.2.50 is on the same /16 local broadcast domain, it sends ARP Who has 192.168.2.50 rather than routing through 192.168.1.1',
        data: 'ARP Request: Who has 192.168.2.50? Tell 192.168.1.10 (No response received, gateway does not proxy ARP)',
        discoveredByCommand: 'tcpdump -i eth0 arp',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ip addr show eth0',
        description: 'Display IP address and CIDR prefix length',
        category: 'DIAGNOSTIC',
        brokenOutput: `eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500\n    inet 192.168.1.10/16 brd 192.168.255.255 scope global eth0\n    valid_lft forever preferred_lft forever`,
        fixedOutput: `eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500\n    inet 192.168.1.10/24 brd 192.168.1.255 scope global eth0\n    valid_lft forever preferred_lft forever`,
        unlocksEvidenceId: 'ev-mask-1',
      },
      {
        command: 'tcpdump -i eth0 arp',
        description: 'Capture ARP packets on interface eth0',
        category: 'INSPECTION',
        brokenOutput: `12:00:01.102 ARP, Request who-has 192.168.2.50 tell 192.168.1.10, length 28\n12:00:02.103 ARP, Request who-has 192.168.2.50 tell 192.168.1.10, length 28`,
        fixedOutput: `12:00:01.102 ARP, Request who-has 192.168.1.1 tell 192.168.1.10, length 28\n12:00:01.103 ARP, Reply 192.168.1.1 is-at 00:1a:2b:11:22:33, length 28`,
        unlocksEvidenceId: 'ev-mask-2',
      },
      {
        command: 'ping 192.168.2.50',
        description: 'Test connectivity to remote server on 192.168.2.0/24 subnet',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 192.168.2.50 (192.168.2.50) 56(84) bytes of data.\nFrom 192.168.1.10 icmp_seq=1 Destination Host Unreachable`,
        fixedOutput: `PING 192.168.2.50 (192.168.2.50) 56(84) bytes of data.\n64 bytes from 192.168.2.50: icmp_seq=1 ttl=63 time=1.45 ms\n64 bytes from 192.168.2.50: icmp_seq=2 ttl=63 time=1.38 ms\n--- 192.168.2.50 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-mask-1',
        description: 'Server-02 has an overly broad subnet mask (/16: 255.255.0.0), causing it to falsely treat 192.168.2.50 as a local on-link host instead of forwarding to the gateway.',
        isCorrect: true,
        explanation: 'When destination IP is in the configured local subnet, the host ARPs directly for the destination MAC rather than sending to the default gateway MAC.',
      },
      {
        id: 'rc-mask-2',
        description: 'The remote server 192.168.2.50 is powered off.',
        isCorrect: false,
        explanation: 'The remote server is active; the client failed to route the packet to the gateway.',
      },
    ],
    hiddenRootCauseId: 'rc-mask-1',
    remediationOptions: [
      {
        id: 'rem-mask-1',
        title: 'Correct Subnet Mask to 255.255.255.0 (/24) on Server-02',
        commandSyntax: 'ip addr add 192.168.1.10/24 dev eth0 && ip addr del 192.168.1.10/16 dev eth0',
        actionDescription: 'Update eth0 interface subnet mask from /16 to /24.',
        isCorrect: true,
        explanation: 'This restores proper boundary detection so 192.168.2.0/24 traffic correctly egresses through gateway 192.168.1.1.',
      },
      {
        id: 'rem-mask-2',
        title: 'Change Gateway IP to 192.168.2.1',
        commandSyntax: 'ip route add default via 192.168.2.1',
        actionDescription: 'Change default gateway to an IP in another subnet.',
        isCorrect: false,
        explanation: 'A host cannot use a default gateway that is not in its own subnet.',
      },
    ],
    correctRemediationId: 'rem-mask-1',
    verificationTests: [
      {
        id: 'test-mask-1',
        name: 'Verify Remote Subnet Ping',
        testCommand: 'ping 192.168.2.50',
        expectedOutputSubstring: '0% packet loss',
        failureMessage: 'Ping to remote subnet 192.168.2.50 failed.',
        successMessage: 'Ping to remote subnet 192.168.2.50 succeeded with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'A /16 subnet mask on a /24 subnet broke inter-subnet routing by forcing direct local ARP requests for remote IP addresses.',
      rootCauseAnalysis: 'Network stacks use the local IP and subnet mask to determine if a destination IP is on-link or remote. A /16 mask meant 192.168.2.50 was considered local, so the host broadcast ARP instead of sending frames to the default gateway MAC.',
      osiLayer: 'Layer 3 (Network)',
      preventionBestPractices: [
        'Enforce consistent subnetting definitions via IPAM (IP Address Management) systems.',
        'Use DHCP/configuration management to prevent manual subnet mask typings.',
      ],
      recommendedCommands: ['ip addr show', 'ip route show', 'tcpdump -i eth0 arp', 'netstat -rn'],
    },
  },

  // 4. ARP Resolution Failure
  {
    id: 'scen-arp-fail',
    slug: 'arp-resolution-failure',
    title: 'ARP Resolution Failure: Stale Static ARP Entry Blocks Gateway Communication',
    incidentDescription:
      'After replacing the core gateway router hardware (new MAC address), Client-01 lost connectivity. Other hosts can reach the new router, but Client-01 fails with "Destination Host Unreachable".',
    category: 'Layer 2 Ethernet & ARP',
    difficulty: 'INTERMEDIATE',
    estimatedMinutes: 15,
    networkingConcepts: ['ARP (Address Resolution Protocol)', 'Layer 2 MAC vs Layer 3 IP', 'Static ARP Cache', 'Gratuitous ARP'],
    initialSymptoms: [
      'Client-01 cannot ping gateway 192.168.1.1',
      'Other workstations on the same switch have no connectivity issues',
      'Client-01 ARP cache shows an old static MAC mapping for 192.168.1.1',
    ],
    topology: {
      nodes: [
        {
          id: 'node-c1',
          name: 'Client-01',
          type: 'pc',
          ipAddress: '192.168.1.100',
          subnetMask: '255.255.255.0',
          defaultGateway: '192.168.1.1',
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-rtr-new',
          name: 'New-Core-Router',
          type: 'router',
          ipAddress: '192.168.1.1',
          macAddress: '00:50:56:AA:BB:CC',
          status: 'online',
          position: { x: 650, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-c1', targetNodeId: 'node-rtr-new', status: 'connected', latencyMs: 1 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-arp-1',
        title: 'Client Static ARP Cache Table',
        category: 'CLI_OUTPUT',
        description: 'Client ARP table has a static entry binding 192.168.1.1 to decommissioned router MAC 00-11-22-33-44-55',
        data: 'Internet Address      Physical Address      Type\n192.168.1.1           00-11-22-33-44-55     static',
        discoveredByCommand: 'arp -a',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'arp -a',
        description: 'View current ARP cache table entries',
        category: 'DIAGNOSTIC',
        brokenOutput: `Interface: 192.168.1.100 --- 0x2\n  Internet Address      Physical Address      Type\n  192.168.1.1           00-11-22-33-44-55     static\n  192.168.1.255         ff-ff-ff-ff-ff-ff     static`,
        fixedOutput: `Interface: 192.168.1.100 --- 0x2\n  Internet Address      Physical Address      Type\n  192.168.1.1           00-50-56-aa-bb-cc     dynamic\n  192.168.1.255         ff-ff-ff-ff-ff-ff     static`,
        unlocksEvidenceId: 'ev-arp-1',
      },
      {
        command: 'ping 192.168.1.1',
        description: 'Ping default gateway',
        category: 'DIAGNOSTIC',
        brokenOutput: `Pinging 192.168.1.1 with 32 bytes of data:\nRequest timed out.\nRequest timed out.\nPackets: Sent = 2, Received = 0, Lost = 2 (100% loss)`,
        fixedOutput: `Pinging 192.168.1.1 with 32 bytes of data:\nReply from 192.168.1.1: bytes=32 time<1ms TTL=64\nReply from 192.168.1.1: bytes=32 time<1ms TTL=64\nPackets: Sent = 2, Received = 2, Lost = 0 (0% loss)`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-arp-1',
        description: 'Client-01 has a hardcoded static ARP entry with the old router MAC address (00-11-22-33-44-55) preventing dynamic ARP resolution to the new router MAC (00-50-56-AA-BB-CC).',
        isCorrect: true,
        explanation: 'Static ARP entries override dynamic ARP requests, sending Ethernet frames to a non-existent MAC address.',
      },
      {
        id: 'rc-arp-2',
        description: 'The Ethernet cable is unplugged.',
        isCorrect: false,
        explanation: 'The link state is UP and local interface is operational.',
      },
    ],
    hiddenRootCauseId: 'rc-arp-1',
    remediationOptions: [
      {
        id: 'rem-arp-1',
        title: 'Delete Static ARP Entry and Allow Dynamic Resolution',
        commandSyntax: 'arp -d 192.168.1.1',
        actionDescription: 'Flush the static ARP table entry for 192.168.1.1.',
        isCorrect: true,
        explanation: 'Flushing the entry allows the host to send an ARP request and learn the new router MAC address dynamically.',
      },
    ],
    correctRemediationId: 'rem-arp-1',
    verificationTests: [
      {
        id: 'test-arp-1',
        name: 'Verify Gateway Communication',
        testCommand: 'ping 192.168.1.1',
        expectedOutputSubstring: '0% loss',
        failureMessage: 'Gateway ping test failed.',
        successMessage: 'Gateway ping test succeeded with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'A legacy static ARP entry on the client prevented communication following router hardware replacement.',
      rootCauseAnalysis: 'Static ARP entries do not expire or update with Gratuitous ARP packets. When router hardware was replaced, Ethernet frames continued targeting the defunct MAC address.',
      osiLayer: 'Layer 2 (Data Link)',
      preventionBestPractices: [
        'Avoid static ARP entries on general endpoints unless required for specialized clustering.',
        'Implement standardized host decommissioning & maintenance scripts.',
      ],
      recommendedCommands: ['arp -a', 'arp -d *', 'ip neigh show', 'ip neigh flush all'],
    },
  },

  // 5. VLAN Mismatch
  {
    id: 'scen-vlan-mismatch',
    slug: 'vlan-mismatch',
    title: 'VLAN Mismatch: Access Port Misassigned to VLAN 20 Instead of Engineering VLAN 10',
    incidentDescription:
      'Workstation-Eng4 in the engineering department cannot communicate with the engineering file server (10.10.10.200) located on VLAN 10.',
    category: 'VLANs & Trunking',
    difficulty: 'INTERMEDIATE',
    estimatedMinutes: 20,
    networkingConcepts: ['802.1Q VLAN Tagging', 'Access vs Trunk Ports', 'Broadcast Domains', 'Switch Port Configuration'],
    initialSymptoms: [
      'Workstation-Eng4 link light is green, IP is statically 10.10.10.45/24',
      'Pings to engineering server 10.10.10.200 time out',
      'Switch port GigabitEthernet0/4 shows up/up',
    ],
    topology: {
      nodes: [
        {
          id: 'node-eng4',
          name: 'Workstation-Eng4',
          type: 'pc',
          ipAddress: '10.10.10.45',
          subnetMask: '255.255.255.0',
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-sw-core',
          name: 'Floor-Switch-01',
          type: 'switch',
          status: 'online',
          position: { x: 450, y: 220 },
        },
        {
          id: 'node-eng-srv',
          name: 'Eng-File-Server (VLAN 10)',
          type: 'server',
          ipAddress: '10.10.10.200',
          subnetMask: '255.255.255.0',
          status: 'online',
          position: { x: 780, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-eng4', targetNodeId: 'node-sw-core', sourcePort: 'eth0', targetPort: 'Gi0/4', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-sw-core', targetNodeId: 'node-eng-srv', sourcePort: 'Gi0/24', targetPort: 'eth0', status: 'connected', latencyMs: 1 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-vlan-1',
        title: 'Switch Port VLAN Membership Output',
        category: 'CLI_OUTPUT',
        description: 'show vlan brief reveals port Gi0/4 is assigned to VLAN 20 (Marketing) instead of VLAN 10 (Engineering)',
        data: 'VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n10   Engineering                      active    Gi0/1, Gi0/2, Gi0/3, Gi0/24\n20   Marketing                        active    Gi0/4, Gi0/5, Gi0/6',
        discoveredByCommand: 'show vlan brief',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'show vlan brief',
        description: 'Display VLAN database and assigned switch ports',
        category: 'INSPECTION',
        brokenOutput: `VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n1    default                          active    Gi0/7-23\n10   Engineering                      active    Gi0/1, Gi0/2, Gi0/3, Gi0/24\n20   Marketing                        active    Gi0/4, Gi0/5, Gi0/6`,
        fixedOutput: `VLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------------\n1    default                          active    Gi0/7-23\n10   Engineering                      active    Gi0/1, Gi0/2, Gi0/3, Gi0/4, Gi0/24\n20   Marketing                        active    Gi0/5, Gi0/6`,
        unlocksEvidenceId: 'ev-vlan-1',
      },
      {
        command: 'ping 10.10.10.200',
        description: 'Test ping to engineering server 10.10.10.200',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 10.10.10.200 (10.10.10.200) 56(84) bytes of data.\nFrom 10.10.10.45 icmp_seq=1 Destination Host Unreachable\n--- 10.10.10.200 ping statistics ---\n2 packets transmitted, 0 received, 100% packet loss`,
        fixedOutput: `PING 10.10.10.200 (10.10.10.200) 56(84) bytes of data.\n64 bytes from 10.10.10.200: icmp_seq=1 ttl=64 time=0.45 ms\n64 bytes from 10.10.10.200: icmp_seq=2 ttl=64 time=0.42 ms\n--- 10.10.10.200 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-vlan-1',
        description: 'Switch port Gi0/4 is configured in VLAN 20 (Marketing) while the host and server communicate on VLAN 10 (Engineering).',
        isCorrect: true,
        explanation: 'Ethernet frames from Gi0/4 are tagged with VLAN 20 and isolated from VLAN 10 devices at Layer 2.',
      },
    ],
    hiddenRootCauseId: 'rc-vlan-1',
    remediationOptions: [
      {
        id: 'rem-vlan-1',
        title: 'Assign Port Gi0/4 to VLAN 10',
        commandSyntax: 'interface GigabitEthernet0/4\n switchport access vlan 10',
        actionDescription: 'Change access VLAN on interface Gi0/4 to VLAN 10.',
        isCorrect: true,
        explanation: 'Placing Gi0/4 into VLAN 10 places Workstation-Eng4 into the same Layer 2 broadcast domain as the engineering server.',
      },
    ],
    correctRemediationId: 'rem-vlan-1',
    verificationTests: [
      {
        id: 'test-vlan-1',
        name: 'Verify File Server Connectivity',
        testCommand: 'ping 10.10.10.200',
        expectedOutputSubstring: '0% packet loss',
        failureMessage: 'Ping to engineering server failed.',
        successMessage: 'Ping to engineering server 10.10.10.200 verified with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'A switch port was misconfigured in VLAN 20 rather than VLAN 10, segmenting Layer 2 traffic between the workstation and server.',
      rootCauseAnalysis: 'VLANs separate Layer 2 broadcast domains. Traffic cannot pass between different VLANs without a Layer 3 router.',
      osiLayer: 'Layer 2 (Data Link)',
      preventionBestPractices: [
        'Use 802.1X dynamic VLAN assignment via RADIUS based on user credentials or device certificates.',
        'Implement port configuration auditing and compliance tooling.',
      ],
      recommendedCommands: ['show vlan brief', 'show interface <int> switchport', 'switchport access vlan <vlan-id>'],
    },
  },

  // 6. STP-Related Loop/Blocking Issue
  {
    id: 'scen-stp-blocking',
    slug: 'stp-loop-blocking-issue',
    title: 'STP Topology Anomaly: Suboptimal Root Bridge Causes Designated Port Flapping & Traffic Drop',
    incidentDescription:
      'Following maintenance, an old access switch was elected Spanning Tree Root Bridge due to default priority 32768 tie-breaking, causing core distribution links to enter BLOCKING/DISCARDING state.',
    category: 'Layer 2 Switching & STP',
    difficulty: 'ADVANCED',
    estimatedMinutes: 20,
    networkingConcepts: ['STP (Spanning Tree Protocol 802.1D/802.1w)', 'Bridge ID & Priority', 'Root Port vs Designated Port vs Blocking Port', 'Forwarding Delay'],
    initialSymptoms: [
      'High packet loss and random 30-second connectivity drops across campus backbone',
      'Switch-Distribution-01 shows root bridge located on edge switch SW-Access-Legacy',
      'Uplink interfaces repeatedly cycling between LEARNING and BLOCKING states',
    ],
    topology: {
      nodes: [
        {
          id: 'node-sw-core',
          name: 'Switch-Core-01',
          type: 'switch',
          status: 'degraded',
          position: { x: 450, y: 150 },
        },
        {
          id: 'node-sw-dist',
          name: 'Switch-Dist-01',
          type: 'switch',
          status: 'online',
          position: { x: 250, y: 300 },
        },
        {
          id: 'node-sw-legacy',
          name: 'SW-Access-Legacy',
          type: 'switch',
          status: 'degraded',
          position: { x: 650, y: 300 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-sw-core', targetNodeId: 'node-sw-dist', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-sw-core', targetNodeId: 'node-sw-legacy', status: 'blocked', latencyMs: 1 },
        { id: 'l3', sourceNodeId: 'node-sw-dist', targetNodeId: 'node-sw-legacy', status: 'connected', latencyMs: 1 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-stp-1',
        title: 'Spanning Tree Topology Output on Core Switch',
        category: 'CLI_OUTPUT',
        description: 'show spanning-tree indicates SW-Access-Legacy with priority 32768 and lower MAC is Root Bridge; Core uplink is BLK',
        data: 'VLAN0001\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    32768\n             Address     0001.0002.0003 (SW-Access-Legacy)\n             Cost        4\n             Port        2 (GigabitEthernet0/2)\n  Bridge ID  Priority    32768\n             Address     0050.56a1.b2c3 (Switch-Core-01)',
        discoveredByCommand: 'show spanning-tree vlan 1',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'show spanning-tree vlan 1',
        description: 'Inspect STP status, root bridge ID, and port roles',
        category: 'INSPECTION',
        brokenOutput: `VLAN0001\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    32768\n             Address     0001.0002.0003\n             This bridge is not the root\n  Interface           Role Sts Cost      Prio.Nbr Type\n  ------------------- ---- --- --------- -------- --------------------------------\n  Gi0/1               Desg FWD 4         128.1    P2p\n  Gi0/2               Altn BLK 4         128.2    P2p`,
        fixedOutput: `VLAN0001\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    4096\n             Address     0050.56a1.b2c3\n             This bridge is the root\n  Interface           Role Sts Cost      Prio.Nbr Type\n  ------------------- ---- --- --------- -------- --------------------------------\n  Gi0/1               Desg FWD 4         128.1    P2p\n  Gi0/2               Desg FWD 4         128.2    P2p`,
        unlocksEvidenceId: 'ev-stp-1',
      },
      {
        command: 'ping 10.0.0.1 -c 10',
        description: 'Test stability of backbone ICMP stream',
        category: 'DIAGNOSTIC',
        brokenOutput: `--- 10.0.0.1 ping statistics ---\n10 packets transmitted, 6 received, 40% packet loss, time 9012ms`,
        fixedOutput: `--- 10.0.0.1 ping statistics ---\n10 packets transmitted, 10 received, 0% packet loss, time 9002ms`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-stp-1',
        description: 'Switch-Core-01 has default STP priority (32768), allowing a lower-MAC legacy access switch to win root bridge election and place primary distribution links in blocking state.',
        isCorrect: true,
        explanation: 'Without configuring primary root priority (4096 or 0), STP ties are broken by lowest MAC address, electing suboptimal root bridges.',
      },
    ],
    hiddenRootCauseId: 'rc-stp-1',
    remediationOptions: [
      {
        id: 'rem-stp-1',
        title: 'Set STP Priority 4096 on Switch-Core-01',
        commandSyntax: 'spanning-tree vlan 1 priority 4096',
        actionDescription: 'Configure Switch-Core-01 with priority 4096 to definitively become the STP Root Bridge.',
        isCorrect: true,
        explanation: 'Low priority forces Switch-Core-01 to win the root bridge election and opens high-speed core links to FORWARDING.',
      },
    ],
    correctRemediationId: 'rem-stp-1',
    verificationTests: [
      {
        id: 'test-stp-1',
        name: 'Verify STP Root Bridge Election',
        testCommand: 'show spanning-tree vlan 1',
        expectedOutputSubstring: 'This bridge is the root',
        failureMessage: 'Switch-Core-01 is not the root bridge.',
        successMessage: 'Switch-Core-01 confirmed as Root Bridge with all core ports in Forwarding state.',
      },
    ],
    postMortem: {
      summary: 'Default STP priority allowed a legacy access switch to win root bridge election, causing core backbone links to be blocked by STP.',
      rootCauseAnalysis: 'STP elects root bridge based on Bridge ID (Priority + MAC). When all switches share default priority 32768, the switch with lowest MAC wins, often an older edge switch.',
      osiLayer: 'Layer 2 (Data Link)',
      preventionBestPractices: [
        'Always configure explicit STP priorities: 4096 for Primary Root and 8192 for Secondary Root.',
        'Enable Root Guard (`spanning-tree guard root`) on all downstream access ports.',
      ],
      recommendedCommands: ['show spanning-tree', 'spanning-tree vlan <id> root primary', 'spanning-tree vlan <id> priority 4096'],
    },
  },

  // 7. OSPF Neighbor Problem
  {
    id: 'scen-ospf-neighbor',
    slug: 'ospf-neighbor-problem',
    title: 'OSPF Neighbor Problem: MTU Mismatch Stalls Adjacency in EXSTART / EXCHANGE State',
    incidentDescription:
      'Router-A and Router-B fail to form a FULL OSPF adjacency over their Gigabit point-to-point link. Routes from Area 0 are not propagating.',
    category: 'Dynamic Routing & OSPF',
    difficulty: 'ADVANCED',
    estimatedMinutes: 20,
    networkingConcepts: ['OSPFv2 Adjacency States', 'Database Description (DBD) Packets', 'Interface MTU Matching', 'Link-State Routing'],
    initialSymptoms: [
      'OSPF neighbor status stuck in EXSTART or EXCHANGE state',
      'No OSPF routes learned in the routing table from the neighbor',
      'Hello packets are received, but Database Description exchange fails',
    ],
    topology: {
      nodes: [
        {
          id: 'node-rtr-a',
          name: 'Router-A (MTU 1500)',
          type: 'router',
          ipAddress: '10.0.0.1',
          status: 'degraded',
          position: { x: 250, y: 220 },
        },
        {
          id: 'node-rtr-b',
          name: 'Router-B (MTU 1400)',
          type: 'router',
          ipAddress: '10.0.0.2',
          status: 'degraded',
          position: { x: 650, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-rtr-a', targetNodeId: 'node-rtr-b', status: 'connected', latencyMs: 2 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-ospf-1',
        title: 'OSPF Neighbor State Output',
        category: 'CLI_OUTPUT',
        description: 'show ip ospf neighbor shows neighbor 10.0.0.2 stuck in EXSTART state',
        data: 'Neighbor ID     Pri   State           Dead Time   Address         Interface\n10.0.0.2          1   EXSTART/ -      00:00:34    10.0.0.2        GigabitEthernet0/1',
        discoveredByCommand: 'show ip ospf neighbor',
        isUnlocked: false,
      },
      {
        id: 'ev-ospf-2',
        title: 'Interface MTU Discrepancy',
        category: 'CONFIG',
        description: 'Router-A has MTU 1500 while Router-B has MTU 1400',
        data: 'Router-A Gi0/1 MTU 1500 bytes\nRouter-B Gi0/1 MTU 1400 bytes',
        discoveredByCommand: 'show interfaces GigabitEthernet0/1',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'show ip ospf neighbor',
        description: 'Display OSPF neighbor adjacency status',
        category: 'INSPECTION',
        brokenOutput: `Neighbor ID     Pri   State           Dead Time   Address         Interface\n10.0.0.2          1   EXSTART/ -      00:00:34    10.0.0.2        GigabitEthernet0/1`,
        fixedOutput: `Neighbor ID     Pri   State           Dead Time   Address         Interface\n10.0.0.2          1   FULL/ -         00:00:38    10.0.0.2        GigabitEthernet0/1`,
        unlocksEvidenceId: 'ev-ospf-1',
      },
      {
        command: 'show interfaces GigabitEthernet0/1',
        description: 'Inspect interface MTU and bandwidth parameters',
        category: 'INSPECTION',
        brokenOutput: `GigabitEthernet0/1 is up, line protocol is up\n  Hardware is Gigabit Ethernet, address is 0050.56a1.0001\n  Internet address is 10.0.0.1/30\n  MTU 1500 bytes, BW 1000000 Kbit/sec`,
        fixedOutput: `GigabitEthernet0/1 is up, line protocol is up\n  Hardware is Gigabit Ethernet, address is 0050.56a1.0001\n  Internet address is 10.0.0.1/30\n  MTU 1500 bytes, BW 1000000 Kbit/sec`,
        unlocksEvidenceId: 'ev-ospf-2',
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-ospf-1',
        description: 'MTU mismatch between Router-A (MTU 1500) and Router-B (MTU 1400) causes OSPF DBD packets to be rejected during the EXSTART negotiation phase.',
        isCorrect: true,
        explanation: 'OSPF DBD packets specify interface MTU. If neighbor MTU exceeds local interface MTU, adjacency negotiation halts in EXSTART.',
      },
    ],
    hiddenRootCauseId: 'rc-ospf-1',
    remediationOptions: [
      {
        id: 'rem-ospf-1',
        title: 'Match MTU to 1500 on Router-B (or enable mtu-ignore)',
        commandSyntax: 'interface GigabitEthernet0/1\n ip mtu 1500',
        actionDescription: 'Configure matching MTU 1500 on both sides of the point-to-point link.',
        isCorrect: true,
        explanation: 'Harmonizing MTU allows DBD packet exchange to complete and adjacency to reach FULL.',
      },
    ],
    correctRemediationId: 'rem-ospf-1',
    verificationTests: [
      {
        id: 'test-ospf-1',
        name: 'Verify OSPF FULL State',
        testCommand: 'show ip ospf neighbor',
        expectedOutputSubstring: 'FULL',
        failureMessage: 'OSPF adjacency did not reach FULL state.',
        successMessage: 'OSPF neighbor state is FULL.',
      },
    ],
    postMortem: {
      summary: 'OSPF adjacency stalled in EXSTART due to an MTU mismatch between peer router interfaces.',
      rootCauseAnalysis: 'During EXSTART/EXCHANGE, routers negotiate master/slave and exchange Database Description (DBD) packets containing interface MTU values. OSPF drops packets when MTUs do not match.',
      osiLayer: 'Layer 3 (Network)',
      preventionBestPractices: [
        'Standardize link MTUs across all point-to-point routing segments.',
        'Use automated config compliance audits for OSPF area and MTU consistency.',
      ],
      recommendedCommands: ['show ip ospf neighbor', 'show ip ospf interface', 'ip mtu <bytes>', 'ip ospf mtu-ignore'],
    },
  },

  // 8. Incorrect Routing Table
  {
    id: 'scen-wrong-route',
    slug: 'incorrect-routing-table',
    title: 'Incorrect Routing Table: Missing Default Gateway Route (0.0.0.0/0) on Edge Router',
    incidentDescription:
      'Internal users on 10.100.0.0/16 can communicate across branch subnets but get "Destination Net Unreachable" for all external public IP traffic.',
    category: 'IP Routing & Forwarding',
    difficulty: 'INTERMEDIATE',
    estimatedMinutes: 15,
    networkingConcepts: ['Routing Table Longest Prefix Match', 'Default Route (Gateway of Last Resort)', 'Static Routes', 'Next-Hop Resolution'],
    initialSymptoms: [
      'Users can reach all internal 10.0.0.0/8 servers',
      'Pings to 8.8.8.8 or public IPs fail with "Destination Net Unreachable"',
      'Edge router route table has no 0.0.0.0/0 entry',
    ],
    topology: {
      nodes: [
        {
          id: 'node-pc-user',
          name: 'Branch-Client',
          type: 'pc',
          ipAddress: '10.100.1.25',
          status: 'online',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-rtr-edge',
          name: 'Edge-Router-01',
          type: 'router',
          ipAddress: '10.100.1.1',
          status: 'degraded',
          position: { x: 450, y: 220 },
        },
        {
          id: 'node-isp-gw',
          name: 'ISP-Gateway',
          type: 'cloud',
          ipAddress: '203.0.113.1',
          status: 'online',
          position: { x: 780, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-pc-user', targetNodeId: 'node-rtr-edge', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-rtr-edge', targetNodeId: 'node-isp-gw', status: 'connected', latencyMs: 5 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-route-1',
        title: 'Edge Router IPv4 Routing Table',
        category: 'CLI_OUTPUT',
        description: 'show ip route reveals "Gateway of last resort is not set" with only internal static routes present',
        data: 'Gateway of last resort is not set\n\nC    10.100.0.0/16 is directly connected, GigabitEthernet0/0\nC    203.0.113.0/30 is directly connected, GigabitEthernet0/1',
        discoveredByCommand: 'show ip route',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'show ip route',
        description: 'Inspect routing table and gateway of last resort',
        category: 'INSPECTION',
        brokenOutput: `Codes: C - connected, S - static\n\nGateway of last resort is not set\n\nC    10.100.0.0/16 is directly connected, GigabitEthernet0/0\nC    203.0.113.0/30 is directly connected, GigabitEthernet0/1`,
        fixedOutput: `Codes: C - connected, S - static, S* - candidate default\n\nGateway of last resort is 203.0.113.1 to network 0.0.0.0\n\nS*   0.0.0.0/0 [1/0] via 203.0.113.1\nC    10.100.0.0/16 is directly connected, GigabitEthernet0/0\nC    203.0.113.0/30 is directly connected, GigabitEthernet0/1`,
        unlocksEvidenceId: 'ev-route-1',
      },
      {
        command: 'ping 8.8.8.8',
        description: 'Ping external internet destination',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 8.8.8.8: 56 data bytes\nFrom 10.100.1.1: icmp_seq=1 Destination Net Unreachable`,
        fixedOutput: `PING 8.8.8.8: 56 data bytes\n64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=12.4 ms\n--- 8.8.8.8 ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-route-1',
        description: 'Edge-Router-01 is missing a default static route (0.0.0.0/0 via 203.0.113.1), causing the router to drop packets destined for non-local networks.',
        isCorrect: true,
        explanation: 'Routers without a default route drop all traffic whose destination IP prefix is not explicitly in the routing table.',
      },
    ],
    hiddenRootCauseId: 'rc-route-1',
    remediationOptions: [
      {
        id: 'rem-route-1',
        title: 'Configure Default Route "ip route 0.0.0.0 0.0.0.0 203.0.113.1"',
        commandSyntax: 'ip route 0.0.0.0 0.0.0.0 203.0.113.1',
        actionDescription: 'Add static default route pointing all unclassified traffic to the upstream ISP next-hop router.',
        isCorrect: true,
        explanation: 'Sets the Gateway of Last Resort on Edge-Router-01 to forward internet traffic to the ISP.',
      },
    ],
    correctRemediationId: 'rem-route-1',
    verificationTests: [
      {
        id: 'test-route-1',
        name: 'Verify Internet Route Ping',
        testCommand: 'ping 8.8.8.8',
        expectedOutputSubstring: '0% packet loss',
        failureMessage: 'Ping to 8.8.8.8 failed.',
        successMessage: 'Default route active; ping to 8.8.8.8 succeeded with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'Edge router dropped outbound internet traffic because the default static route (0.0.0.0/0) was missing.',
      rootCauseAnalysis: 'Routers perform Longest Prefix Match. When an IP does not match any specific route and no 0.0.0.0/0 default route exists, the packet is discarded and an ICMP Destination Net Unreachable is returned.',
      osiLayer: 'Layer 3 (Network)',
      preventionBestPractices: [
        'Include default route verification in edge router baseline provisioning.',
        'Use dynamic routing (BGP/OSPF default-information originate) where applicable.',
      ],
      recommendedCommands: ['show ip route', 'ip route 0.0.0.0 0.0.0.0 <next-hop>', 'traceroute <ip>'],
    },
  },

  // 9. Packet-Loss Scenario
  {
    id: 'scen-packet-loss',
    slug: 'packet-loss-duplex-mismatch',
    title: 'Severe Packet Loss: Half-Duplex vs Full-Duplex Mismatch Induces Collisions & CRC Errors',
    incidentDescription:
      'Database replication over link Gi0/1 experiences 35% packet loss, frequent TCP resets, and severe throughput collapse under load.',
    category: 'Layer 1/2 Physical & Data Link',
    difficulty: 'INTERMEDIATE',
    estimatedMinutes: 20,
    networkingConcepts: ['Duplex Mismatch (Half vs Full)', 'Carrier Sense Multiple Access with Collision Detection (CSMA/CD)', 'Late Collisions', 'FCS/CRC Errors'],
    initialSymptoms: [
      'High intermittent packet loss (30-40%) between switch and database server',
      'Small ping packets sometimes pass, but file transfers crawl and drop',
      'Interface statistics show thousands of Late Collisions and CRC Frame Check Sequence errors',
    ],
    topology: {
      nodes: [
        {
          id: 'node-sw-dist',
          name: 'Dist-Switch (Full-Duplex)',
          type: 'switch',
          status: 'online',
          position: { x: 250, y: 220 },
        },
        {
          id: 'node-db-srv',
          name: 'Database-Server (Half-Duplex)',
          type: 'server',
          ipAddress: '10.0.50.10',
          status: 'degraded',
          position: { x: 650, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-sw-dist', targetNodeId: 'node-db-srv', status: 'degraded', packetLossPercent: 35, latencyMs: 1 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-loss-1',
        title: 'Database Server NIC Duplex Configuration',
        category: 'INTERFACE_METRIC',
        description: 'ethtool eth0 output shows Duplex: Half and Auto-negotiation: off on Database-Server',
        data: 'Speed: 100Mb/s\nDuplex: Half\nAuto-negotiation: off\nCollisions: 48,219\nLate Collisions: 12,840',
        discoveredByCommand: 'ethtool eth0',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ethtool eth0',
        description: 'Inspect physical NIC link speed, duplex mode, and auto-negotiation',
        category: 'INSPECTION',
        brokenOutput: `Settings for eth0:\n  Supported ports: [ TP ]\n  Speed: 100Mb/s\n  Duplex: Half\n  Auto-negotiation: off\n  Link detected: yes`,
        fixedOutput: `Settings for eth0:\n  Supported ports: [ TP ]\n  Speed: 1000Mb/s\n  Duplex: Full\n  Auto-negotiation: on\n  Link detected: yes`,
        unlocksEvidenceId: 'ev-loss-1',
      },
      {
        command: 'ping 10.0.50.10 -c 10',
        description: 'Measure packet loss and latency stability',
        category: 'DIAGNOSTIC',
        brokenOutput: `--- 10.0.50.10 ping statistics ---\n10 packets transmitted, 6 received, 40% packet loss, time 9015ms`,
        fixedOutput: `--- 10.0.50.10 ping statistics ---\n10 packets transmitted, 10 received, 0% packet loss, time 9003ms`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-loss-1',
        description: 'A duplex mismatch (Switch is Full-Duplex while Server is hardcoded to Half-Duplex) causes continuous collisions and CRC frame discards when both ends transmit simultaneously.',
        isCorrect: true,
        explanation: 'In half-duplex mode, receiving a frame while transmitting is treated as a collision, aborting transmission and generating late collisions.',
      },
    ],
    hiddenRootCauseId: 'rc-loss-1',
    remediationOptions: [
      {
        id: 'rem-loss-1',
        title: 'Enable Auto-Negotiation (Full-Duplex 1000Mb/s) on Database Server',
        commandSyntax: 'ethtool -s eth0 autoneg on speed 1000 duplex full',
        actionDescription: 'Enable auto-negotiation and Full-Duplex mode on the server NIC.',
        isCorrect: true,
        explanation: 'Matching full-duplex operation eliminates collisions and restores lossless throughput.',
      },
    ],
    correctRemediationId: 'rem-loss-1',
    verificationTests: [
      {
        id: 'test-loss-1',
        name: 'Verify Zero Packet Loss Over 10 Pings',
        testCommand: 'ping 10.0.50.10 -c 10',
        expectedOutputSubstring: '0% packet loss',
        failureMessage: 'Packet loss persists.',
        successMessage: 'Full duplex verified; 10/10 packets received with 0% loss.',
      },
    ],
    postMortem: {
      summary: 'Hardcoded half-duplex configuration on the server created a duplex mismatch with the switch, producing severe collision-induced packet loss.',
      rootCauseAnalysis: 'Ethernet full-duplex allows simultaneous bidirectional transmission without collision detection. When one side is half-duplex, it interprets incoming traffic during its own transmission as collisions, corrupting frames.',
      osiLayer: 'Layer 1/2 (Physical & Data Link)',
      preventionBestPractices: [
        'Always leave Ethernet auto-negotiation enabled across all modern copper/fiber switchports and server NICs.',
        'Alert on switchport collision counter and FCS error increments in SNMP monitoring.',
      ],
      recommendedCommands: ['ethtool <int>', 'show interfaces <int>', 'netstat -i', 'ip -s link'],
    },
  },

  // 10. MTU Mismatch
  {
    id: 'scen-mtu-blackhole',
    slug: 'mtu-mismatch-pmtud-blackhole',
    title: 'MTU Mismatch & PMTUD Black Hole: Small Pings Succeed, Large HTTPS Payloads Drop',
    incidentDescription:
      'Branch users can ping the corporate web portal (ICMP 64 bytes), but loading the web page in HTTPS hangs indefinitely at TLS handshake due to a 1400 MTU WAN tunnel dropping DF-flagged frames.',
    category: 'Transport & PMTUD',
    difficulty: 'ADVANCED',
    estimatedMinutes: 20,
    networkingConcepts: ['Maximum Transmission Unit (MTU)', 'Path MTU Discovery (PMTUD)', 'DF (Don\'t Fragment) Bit', 'TCP MSS Clamping'],
    initialSymptoms: [
      'ping portal.corp.lan (small 32/64 byte packets) works with 0% loss',
      'ping portal.corp.lan -l 1472 -f (large packets with DF bit) fails with "Packet needs to be fragmented but DF set"',
      'HTTPS web page loads stall during TLS certificate transfer',
    ],
    topology: {
      nodes: [
        {
          id: 'node-client',
          name: 'Branch-Client (MTU 1500)',
          type: 'pc',
          ipAddress: '192.168.10.50',
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-vpn-gw',
          name: 'VPN-Router (Tunnel MTU 1400)',
          type: 'router',
          ipAddress: '192.168.10.1',
          status: 'online',
          position: { x: 450, y: 220 },
        },
        {
          id: 'node-web-corp',
          name: 'Corporate-Portal (MTU 1500)',
          type: 'server',
          ipAddress: '10.0.0.100',
          status: 'online',
          position: { x: 780, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-client', targetNodeId: 'node-vpn-gw', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-vpn-gw', targetNodeId: 'node-web-corp', status: 'connected', latencyMs: 15 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-mtu-1',
        title: 'DF Ping Sweep Telemetry',
        category: 'CLI_OUTPUT',
        description: 'Large ICMP echo with Don\'t Fragment bit reveals MTU bottleneck at 1400 bytes',
        data: 'Packet needs to be fragmented but DF set.\nMTU exceeded on intermediate tunnel interface.',
        discoveredByCommand: 'ping 10.0.0.100 -l 1450 -f',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ping 10.0.0.100',
        description: 'Standard small ICMP ping test',
        category: 'DIAGNOSTIC',
        brokenOutput: `Pinging 10.0.0.100 with 32 bytes of data:\nReply from 10.0.0.100: bytes=32 time=15ms TTL=62\nReply from 10.0.0.100: bytes=32 time=15ms TTL=62`,
        fixedOutput: `Pinging 10.0.0.100 with 32 bytes of data:\nReply from 10.0.0.100: bytes=32 time=15ms TTL=62`,
      },
      {
        command: 'ping 10.0.0.100 -l 1450 -f',
        description: 'Ping with 1450 byte payload and Don\'t Fragment (DF) bit set',
        category: 'DIAGNOSTIC',
        brokenOutput: `Pinging 10.0.0.100 with 1450 bytes of data:\nPacket needs to be fragmented but DF set.\nPacket needs to be fragmented but DF set.`,
        fixedOutput: `Pinging 10.0.0.100 with 1450 bytes of data:\nReply from 10.0.0.100: bytes=1450 time=16ms TTL=62`,
        unlocksEvidenceId: 'ev-mtu-1',
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-mtu-1',
        description: 'The intermediate VPN tunnel MTU is 1400 bytes. Because clients set the DF (Don\'t Fragment) bit and intermediate ICMP Fragmentation Needed messages are dropped, Path MTU Discovery fails (PMTUD Black Hole).',
        isCorrect: true,
        explanation: 'Oversized packets cannot be fragmented when DF=1 and are silently dropped, causing TLS handshakes to hang.',
      },
    ],
    hiddenRootCauseId: 'rc-mtu-1',
    remediationOptions: [
      {
        id: 'rem-mtu-1',
        title: 'Configure TCP MSS Clamping to 1360 on VPN Router',
        commandSyntax: 'interface Tunnel1\n ip tcp adjust-mss 1360',
        actionDescription: 'Clamp TCP Maximum Segment Size (MSS) in SYN packets to 1360 bytes on the VPN router interface.',
        isCorrect: true,
        explanation: 'MSS clamping forces TCP endpoints to negotiate smaller segments that fit within the 1400-byte tunnel without fragmentation.',
      },
    ],
    correctRemediationId: 'rem-mtu-1',
    verificationTests: [
      {
        id: 'test-mtu-1',
        name: 'Verify Large Payload Transport',
        testCommand: 'ping 10.0.0.100 -l 1450 -f',
        expectedOutputSubstring: 'Reply from 10.0.0.100',
        failureMessage: 'Large frame transport failed.',
        successMessage: 'Large frame transport and TCP MSS negotiation operational.',
      },
    ],
    postMortem: {
      summary: 'Intermediate VPN tunnel overhead reduced path MTU to 1400 bytes, dropping large TLS handshake packets.',
      rootCauseAnalysis: 'When IPsec/GRE encapsulation reduces path MTU, endpoints transmitting with DF=1 need ICMP Type 3 Code 4 (Fragmentation Needed) to discover the path MTU. When firewalls block ICMP, PMTUD black hole occurs.',
      osiLayer: 'Layer 3/4 (Network & Transport)',
      preventionBestPractices: [
        'Apply `ip tcp adjust-mss 1360` on all VPN and GRE tunnel interfaces.',
        'Never block ICMP Type 3 Code 4 (Fragmentation Needed) on perimeter firewalls.',
      ],
      recommendedCommands: ['ping <ip> -l <size> -f', 'ip tcp adjust-mss <mss>', 'tracepath <ip>'],
    },
  },

  // 11. High-Latency Scenario
  {
    id: 'scen-bufferbloat',
    slug: 'high-latency-bufferbloat',
    title: 'High Latency & Bufferbloat: Unmanaged Queue Overruns Spike RTT to 850ms Under Load',
    incidentDescription:
      'Voice over IP (VoIP) calls experience extreme jitter, echo, and robotic audio whenever large file uploads occur across the 20Mbps branch WAN circuit.',
    category: 'QoS & Performance',
    difficulty: 'ADVANCED',
    estimatedMinutes: 20,
    networkingConcepts: ['Bufferbloat', 'Queue Management (FIFO vs CoDel/FQ-CoDel)', 'Quality of Service (QoS)', 'Traffic Shaping vs Policing'],
    initialSymptoms: [
      'Idle ping latency is 15ms; when file transfers begin, latency spikes to 850ms with 20% packet drops',
      'VoIP packets stuck behind bulk file transfer queues in router FIFO buffer',
    ],
    topology: {
      nodes: [
        {
          id: 'node-voip-phone',
          name: 'VoIP-Phone-01',
          type: 'pc',
          ipAddress: '192.168.1.20',
          status: 'degraded',
          position: { x: 120, y: 220 },
        },
        {
          id: 'node-rtr-wan',
          name: 'Branch-WAN-Router (FIFO Queue)',
          type: 'router',
          ipAddress: '192.168.1.1',
          status: 'degraded',
          position: { x: 450, y: 220 },
        },
        {
          id: 'node-pbx-cloud',
          name: 'Cloud-PBX-Server',
          type: 'server',
          ipAddress: '198.51.100.10',
          status: 'online',
          position: { x: 780, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-voip-phone', targetNodeId: 'node-rtr-wan', status: 'connected', latencyMs: 1 },
        { id: 'l2', sourceNodeId: 'node-rtr-wan', targetNodeId: 'node-pbx-cloud', status: 'degraded', latencyMs: 850 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-lat-1',
        title: 'Router Queue Statistics',
        category: 'INTERFACE_METRIC',
        description: 'show interface GigabitEthernet0/1 reveals oversized FIFO queue holding 2000 packets with 800ms buffer latency',
        data: 'Queueing strategy: fifo\n  Output queue: 1842/2000/0 (size/max total/drops)\n  Average queue delay: 845 ms',
        discoveredByCommand: 'show interface GigabitEthernet0/1',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'show interface GigabitEthernet0/1',
        description: 'Inspect interface queue depth and buffering strategy',
        category: 'INSPECTION',
        brokenOutput: `GigabitEthernet0/1 is up, line protocol is up\n  Queueing strategy: fifo\n  Output queue: 1842/2000/0 (size/max total/drops)\n  Average queue delay: 845 ms`,
        fixedOutput: `GigabitEthernet0/1 is up, line protocol is up\n  Queueing strategy: fair-queue (FQ-CoDel / Priority Queue for DSCP EF)\n  Output queue: 12/64/0 (size/max total/drops)\n  Average queue delay: 16 ms`,
        unlocksEvidenceId: 'ev-lat-1',
      },
      {
        command: 'ping 198.51.100.10 -c 5',
        description: 'Test round-trip latency to Cloud PBX',
        category: 'DIAGNOSTIC',
        brokenOutput: `PING 198.51.100.10: 56 data bytes\n64 bytes from 198.51.100.10: icmp_seq=1 time=842 ms\n64 bytes from 198.51.100.10: icmp_seq=2 time=865 ms\n--- 198.51.100.10 ping statistics ---\n5 packets transmitted, 5 received, 0% loss, rtt avg = 853 ms`,
        fixedOutput: `PING 198.51.100.10: 56 data bytes\n64 bytes from 198.51.100.10: icmp_seq=1 time=15.2 ms\n64 bytes from 198.51.100.10: icmp_seq=2 time=14.9 ms\n--- 198.51.100.10 ping statistics ---\n5 packets transmitted, 5 received, 0% loss, rtt avg = 15.1 ms`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-lat-1',
        description: 'Bufferbloat caused by an unmanaged, oversized FIFO queue on the WAN uplink, resulting in high latency spikes as real-time VoIP packets wait behind bulk TCP transfer buffers.',
        isCorrect: true,
        explanation: 'Deep FIFO queues prevent TCP congestion backoff and delay delay-sensitive traffic.',
      },
    ],
    hiddenRootCauseId: 'rc-lat-1',
    remediationOptions: [
      {
        id: 'rem-lat-1',
        title: 'Apply QoS Low Latency Queuing (LLQ) & FQ-CoDel Shape Policy',
        commandSyntax: 'policy-map WAN-QOS\n class VOIP\n  priority 4000\n class class-default\n  fair-queue',
        actionDescription: 'Configure QoS priority queuing for voice traffic (DSCP EF) and active queue management for best-effort traffic.',
        isCorrect: true,
        explanation: 'Prioritizing voice traffic and managing queue depth drops latency from 850ms back down to under 20ms.',
      },
    ],
    correctRemediationId: 'rem-lat-1',
    verificationTests: [
      {
        id: 'test-lat-1',
        name: 'Verify Latency Restored to Under 30ms',
        testCommand: 'ping 198.51.100.10 -c 5',
        expectedOutputSubstring: 'avg = 15.',
        failureMessage: 'Latency remains elevated.',
        successMessage: 'Latency normalized to 15ms under QoS management.',
      },
    ],
    postMortem: {
      summary: 'Excessive FIFO output buffers on the WAN router caused bufferbloat, creating 850ms latency spikes for real-time VoIP traffic.',
      rootCauseAnalysis: 'Bufferbloat occurs when routers have excessive unmanaged buffers that fill up during bulk transfers, destroying interactive and real-time application performance.',
      osiLayer: 'Layer 3/4 (Network & Transport)',
      preventionBestPractices: [
        'Deploy Active Queue Management (AQM) such as FQ-CoDel or CAKE on WAN edges.',
        'Implement Low-Latency Queuing (LLQ) with DSCP Expedited Forwarding (EF) for voice.',
      ],
      recommendedCommands: ['show policy-map interface', 'show queueing interface', 'ping <ip> -s <size>'],
    },
  },

  // 12. TCP Connection Failure
  {
    id: 'scen-tcp-rst',
    slug: 'tcp-connection-failure',
    title: 'TCP Connection Failure: Localhost Bind Misconfiguration Sends TCP RST',
    incidentDescription:
      'Clients connecting to the internal inventory API service on port 8443 receive immediate "Connection Refused" (TCP RST) errors, even though the backend node process is running.',
    category: 'Transport & Sockets',
    difficulty: 'INTERMEDIATE',
    estimatedMinutes: 15,
    networkingConcepts: ['TCP 3-Way Handshake (SYN, SYN-ACK, ACK)', 'TCP RST (Reset) Flag', 'Socket Binding (127.0.0.1 vs 0.0.0.0)', 'Listening Sockets'],
    initialSymptoms: [
      'curl https://10.0.0.50:8443 returns "Failed to connect: Connection refused"',
      'Process manager confirms node server.js is active with PID 4120',
      'Packet trace shows server immediately returns TCP RST flag in response to client SYN',
    ],
    topology: {
      nodes: [
        {
          id: 'node-client-app',
          name: 'Client-App',
          type: 'pc',
          ipAddress: '10.0.0.10',
          status: 'online',
          position: { x: 150, y: 220 },
        },
        {
          id: 'node-api-server',
          name: 'Inventory-API-Server',
          type: 'server',
          ipAddress: '10.0.0.50',
          status: 'degraded',
          position: { x: 650, y: 220 },
        },
      ],
      links: [
        { id: 'l1', sourceNodeId: 'node-client-app', targetNodeId: 'node-api-server', status: 'connected', latencyMs: 1 },
      ],
    },
    evidenceItems: [
      {
        id: 'ev-tcp-1',
        title: 'Server Active Socket Listeners',
        category: 'CLI_OUTPUT',
        description: 'netstat / ss output confirms application is bound exclusively to loopback 127.0.0.1:8443 instead of all interfaces 0.0.0.0:8443',
        data: 'Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program\ntcp        0      0 127.0.0.1:8443          0.0.0.0:*               LISTEN      4120/node',
        discoveredByCommand: 'ss -tulpn',
        isUnlocked: false,
      },
    ],
    allowedCommands: [
      {
        command: 'ss -tulpn',
        description: 'Inspect listening TCP/UDP sockets and process bindings',
        category: 'INSPECTION',
        brokenOutput: `Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:PortProcess\ntcp   LISTEN 0      128    127.0.0.1:8443      0.0.0.0:*        users:(("node",pid=4120,fd=18))\ntcp   LISTEN 0      128    0.0.0.0:22          0.0.0.0:*        users:(("sshd",pid=840,fd=3))`,
        fixedOutput: `Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:PortProcess\ntcp   LISTEN 0      128    0.0.0.0:8443        0.0.0.0:*        users:(("node",pid=4120,fd=18))\ntcp   LISTEN 0      128    0.0.0.0:22          0.0.0.0:*        users:(("sshd",pid=840,fd=3))`,
        unlocksEvidenceId: 'ev-tcp-1',
      },
      {
        command: 'curl -k https://10.0.0.50:8443/health',
        description: 'Test HTTP over TLS socket connection to API endpoint',
        category: 'DIAGNOSTIC',
        brokenOutput: `curl: (7) Failed to connect to 10.0.0.50 port 8443: Connection refused`,
        fixedOutput: `HTTP/1.1 200 OK\nContent-Type: application/json\n{"status":"healthy","service":"inventory-api","version":"1.4.0"}`,
      },
    ],
    rootCauseOptions: [
      {
        id: 'rc-tcp-1',
        description: 'The API server process is bound exclusively to the loopback interface (127.0.0.1:8443), causing the kernel TCP stack to send TCP RST (Connection Refused) for external interface (10.0.0.50) SYN packets.',
        isCorrect: true,
        explanation: 'Sockets bound to 127.0.0.1 only accept connections originating from the local host.',
      },
    ],
    hiddenRootCauseId: 'rc-tcp-1',
    remediationOptions: [
      {
        id: 'rem-tcp-1',
        title: 'Rebind Application Socket to 0.0.0.0:8443 (All Interfaces)',
        commandSyntax: 'export HOST=0.0.0.0 && systemctl restart inventory-api',
        actionDescription: 'Update application listen host to 0.0.0.0 and restart the service.',
        isCorrect: true,
        explanation: 'Binding to 0.0.0.0 enables the socket to accept incoming TCP SYN packets on all network interfaces.',
      },
    ],
    correctRemediationId: 'rem-tcp-1',
    verificationTests: [
      {
        id: 'test-tcp-1',
        name: 'Verify API Health Check',
        testCommand: 'curl -k https://10.0.0.50:8443/health',
        expectedOutputSubstring: '"status":"healthy"',
        failureMessage: 'API connection failed.',
        successMessage: 'API health endpoint returned 200 OK.',
      },
    ],
    postMortem: {
      summary: 'The application socket was bound only to localhost 127.0.0.1, causing the OS kernel to reject external connections with TCP RST.',
      rootCauseAnalysis: 'When a TCP SYN arrives for a port without an active listening socket on that IP address, the kernel generates an immediate TCP RST packet with ACK=seq+1.',
      osiLayer: 'Layer 4 (Transport)',
      preventionBestPractices: [
        'Use environment variables to configure bind addresses (`HOST=0.0.0.0` for containers/servers).',
        'Verify listening sockets with `ss -tulpn` or `netstat -tlpn` during deployment health checks.',
      ],
      recommendedCommands: ['ss -tulpn', 'curl -v <url>', 'tcpdump -i any port <port>', 'netstat -ano'],
    },
  },
];
