import { CourseLevel, LessonType } from '@prisma/client';

export interface TargetCourseDefinition {
  code: string;
  slug: string;
  order: number;
  title: string;
  tagline: string;
  category: string;
  description: string;
  level: CourseLevel;
  icon: string;
  estimatedHours: number;
  prerequisitesJson: string[];
  moduleTitle: string;
  moduleDescription: string;
}

export const TARGET_16_COURSES: TargetCourseDefinition[] = [
  // LEVEL 0 — FOUNDATIONS (100 Series)
  {
    code: 'NET-101',
    slug: 'net-101-digital-foundations',
    order: 1,
    title: 'Computer & Digital Information Foundations',
    tagline: 'Master bits, bytes, binary arithmetic, hexadecimal notation, and computer hardware components.',
    category: 'Foundations',
    description: 'Zero-prerequisite foundation course covering binary numbers, hexadecimal conversion, CPU/RAM/NIC hardware architecture, and terminal navigation.',
    level: CourseLevel.FOUNDATIONAL,
    icon: 'Binary',
    estimatedHours: 4,
    prerequisitesJson: [],
    moduleTitle: 'Module 1: Digital Representation & Binary Arithmetic',
    moduleDescription: 'Understand how digital data is represented in binary bits, hex bytes, and hardware interfaces.',
  },
  {
    code: 'NET-102',
    slug: 'net-102-network-fundamentals',
    order: 2,
    title: 'Network Fundamentals & Telecommunications',
    tagline: 'Understand connected systems, network boundaries, topology geometry, and transmission media.',
    category: 'Foundations',
    description: 'Foundational introduction to local networks, wide area networks, topology arrangements, and transmission media.',
    level: CourseLevel.FOUNDATIONAL,
    icon: 'Network',
    estimatedHours: 5,
    prerequisitesJson: ['NET-101'],
    moduleTitle: 'Module 1: Interconnected Nodes & Physical Topologies',
    moduleDescription: 'Learn how hosts connect across star, mesh, and bus topologies.',
  },
  {
    code: 'NET-103',
    slug: 'net-103-reference-models',
    order: 3,
    title: 'The OSI & TCP/IP Reference Models',
    tagline: 'Master the 7-layer OSI model and 4-layer TCP/IP architectural frameworks.',
    category: 'Foundations',
    description: 'Deep architectural exploration of layered networking, protocol data units (PDUs), and data encapsulation.',
    level: CourseLevel.FOUNDATIONAL,
    icon: 'Layers',
    estimatedHours: 5,
    prerequisitesJson: ['NET-102'],
    moduleTitle: 'Module 1: Architectural Layering & Data Encapsulation',
    moduleDescription: 'Master the 7 layers of OSI and 4 layers of TCP/IP protocol suites.',
  },

  // LEVEL 1 — BEGINNER NETWORKING (200 Series)
  {
    code: 'NET-201',
    slug: 'net-201-layer2-ethernet',
    order: 4,
    title: 'Layer 2 Ethernet & Physical Media',
    tagline: 'Master Ethernet 802.3 framing, MAC addressing, OUI structure, and Layer 2 switching.',
    category: 'Beginner',
    description: 'Detailed study of Ethernet frames, MAC address tables, collision domains, and physical layer cables.',
    level: CourseLevel.BEGINNER,
    icon: 'Cpu',
    estimatedHours: 6,
    prerequisitesJson: ['NET-103'],
    moduleTitle: 'Module 1: Ethernet Framing & MAC Addressing',
    moduleDescription: 'Understand physical hardware identity, MAC tables, and Ethernet frame headers.',
  },
  {
    code: 'NET-202',
    slug: 'net-202-ipv4-subnetting',
    order: 5,
    title: 'IPv4 Addressing & CIDR Subnetting Mastery',
    tagline: 'Master 32-bit IPv4 structure, subnet masks, CIDR notation, and VLSM network partitioning.',
    category: 'Beginner',
    description: 'Comprehensive guide to IPv4 binary structure, network vs host boundaries, CIDR slash notation, and subnetting calculations.',
    level: CourseLevel.BEGINNER,
    icon: 'Hash',
    estimatedHours: 8,
    prerequisitesJson: ['NET-101', 'NET-103'],
    moduleTitle: 'Module 1: IPv4 Structure & Subnetting Mechanics',
    moduleDescription: 'Master IPv4 octets, subnet masks, wildcard masks, and CIDR network calculations.',
  },
  {
    code: 'NET-203',
    slug: 'net-203-core-ip-services',
    order: 6,
    title: 'Core IP Services (ARP, ICMP, DNS, DHCP)',
    tagline: 'Master resolution, diagnostic, and provisioning protocols powering local and global networks.',
    category: 'Beginner',
    description: 'Detailed study of Address Resolution Protocol (ARP), ICMP pings, DNS domain resolution, and DHCP DORA address leases.',
    level: CourseLevel.BEGINNER,
    icon: 'Server',
    estimatedHours: 7,
    prerequisitesJson: ['NET-201', 'NET-202'],
    moduleTitle: 'Module 1: Resolution & Provisioning Protocols',
    moduleDescription: 'Learn how ARP resolves MACs, ICMP diagnostics operate, and DHCP/DNS automate client connectivity.',
  },
  {
    code: 'NET-204',
    slug: 'net-204-transport-protocols',
    order: 7,
    title: 'Transport Layer Protocols (TCP & UDP)',
    tagline: 'Master TCP 3-way handshakes, sequence numbers, port sockets, and UDP datagram mechanics.',
    category: 'Beginner',
    description: 'Deep dive into Layer 4 reliable stream transport (TCP), 3-way connection handshakes, sequence/ack numbers, and datagram transport (UDP).',
    level: CourseLevel.BEGINNER,
    icon: 'Activity',
    estimatedHours: 6,
    prerequisitesJson: ['NET-203'],
    moduleTitle: 'Module 1: Sockets & Reliable Transport',
    moduleDescription: 'Understand TCP control flags, port socket bindings, flow control, and UDP performance.',
  },

  // LEVEL 2 — INTERMEDIATE NETWORKING (300 Series)
  {
    code: 'NET-301',
    slug: 'net-301-switching-vlans',
    order: 8,
    title: 'Enterprise Switching, VLANs & Trunking',
    tagline: 'Master Layer 2 VLAN partitioning, IEEE 802.1Q trunking headers, and inter-VLAN routing.',
    category: 'Intermediate',
    description: 'Configure and troubleshoot Virtual LANs (VLANs), 802.1Q VLAN tagging headers, trunk interfaces, and router-on-a-stick inter-VLAN routing.',
    level: CourseLevel.INTERMEDIATE,
    icon: 'ToggleLeft',
    estimatedHours: 8,
    prerequisitesJson: ['NET-201'],
    moduleTitle: 'Module 1: LAN Switching & VLAN Isolation',
    moduleDescription: 'Learn how switches partition broadcast domains using VLAN IDs and 802.1Q trunk lines.',
  },
  {
    code: 'NET-302',
    slug: 'net-302-spanning-tree',
    order: 9,
    title: 'Spanning Tree Protocol & Switch Redundancy',
    tagline: 'Master IEEE 802.1D Spanning Tree Protocol (STP), BPDU messages, and loop prevention.',
    category: 'Intermediate',
    description: 'Prevent Layer 2 broadcast storms using Spanning Tree Protocol (STP), root bridge election, port roles (Root, Designated, Blocking), and Rapid STP.',
    level: CourseLevel.INTERMEDIATE,
    icon: 'GitBranch',
    estimatedHours: 6,
    prerequisitesJson: ['NET-301'],
    moduleTitle: 'Module 1: Loop Prevention & STP Mechanics',
    moduleDescription: 'Master Root Bridge election, BPDU frame propagation, and STP convergence timers.',
  },
  {
    code: 'NET-303',
    slug: 'net-303-static-routing',
    order: 10,
    title: 'IP Routing & Static Route Administration',
    tagline: 'Master Layer 3 packet forwarding, routing table lookup algorithms, and static routes.',
    category: 'Intermediate',
    description: 'Administer router interfaces, routing table inspection, longest prefix matching rules, default static routes (0.0.0.0/0), and next-hop forwarding.',
    level: CourseLevel.INTERMEDIATE,
    icon: 'Share2',
    estimatedHours: 7,
    prerequisitesJson: ['NET-202'],
    moduleTitle: 'Module 1: Layer 3 Packet Forwarding & Routing Tables',
    moduleDescription: 'Understand how routers evaluate destination IP addresses against routing table entries.',
  },
  {
    code: 'NET-304',
    slug: 'net-304-dynamic-routing-ospf',
    order: 11,
    title: 'Dynamic Routing Protocols (Single-Area OSPF)',
    tagline: 'Master Open Shortest Path First (OSPFv2), link-state advertisements, and Dijkstra algorithm.',
    category: 'Intermediate',
    description: 'Learn dynamic interior gateway routing protocols, OSPF neighbor adjacencies, Hello packets, LSA flooding, and Shortest Path First calculations.',
    level: CourseLevel.INTERMEDIATE,
    icon: 'Globe',
    estimatedHours: 8,
    prerequisitesJson: ['NET-303'],
    moduleTitle: 'Module 1: OSPF Adjacencies & Path Determination',
    moduleDescription: 'Master single-area OSPFv2 neighbor formation, cost metrics, and link-state databases.',
  },
  {
    code: 'NET-305',
    slug: 'net-305-acls-firewalls',
    order: 12,
    title: 'Network Security, ACLs & Stateful Firewalls',
    tagline: 'Master IP Access Control Lists (ACLs), wildcard masks, stateful firewall inspection, and security policies.',
    category: 'Intermediate',
    description: 'Enforce perimeter security using standard and extended IPv4 ACLs, wildcard mask filtering, stateful connection tracking, and security zone rules.',
    level: CourseLevel.INTERMEDIATE,
    icon: 'Shield',
    estimatedHours: 8,
    prerequisitesJson: ['NET-303'],
    moduleTitle: 'Module 1: Packet Filtering & Perimeter Security',
    moduleDescription: 'Learn how routers and stateful firewalls evaluate IP/Port traffic against access lists.',
  },

  // LEVEL 3 — ADVANCED NETWORKING (400 Series)
  {
    code: 'NET-401',
    slug: 'net-401-nat-pat',
    order: 13,
    title: 'NAT, PAT & Edge WAN Connectivity',
    tagline: 'Master Static NAT, Dynamic NAT, Port Address Translation (PAT/NAPT), and ISP edge routing.',
    category: 'Advanced',
    description: 'Conserve IPv4 address space using Static NAT, Dynamic NAT pools, Port Address Translation (Overload/PAT), and edge router translation tables.',
    level: CourseLevel.ADVANCED,
    icon: 'Shuffle',
    estimatedHours: 6,
    prerequisitesJson: ['NET-303'],
    moduleTitle: 'Module 1: Network Address Translation & Port Address Translation',
    moduleDescription: 'Understand Inside Local, Inside Global, Outside Global, and Outside Local address translation.',
  },
  {
    code: 'NET-402',
    slug: 'net-402-vpn-crypto',
    order: 14,
    title: 'VPN Technology & Cryptography',
    tagline: 'Master IPsec VPN tunnels, ISAKMP IKE Phase 1/2 negotiation, AES encryption, and Diffie-Hellman.',
    category: 'Advanced',
    description: 'Secure site-to-site WAN communication using IPsec tunnels, IKE Phase 1/Phase 2 SA negotiation, AES/RSA cryptography, and Diffie-Hellman key exchange.',
    level: CourseLevel.ADVANCED,
    icon: 'Lock',
    estimatedHours: 7,
    prerequisitesJson: ['NET-305'],
    moduleTitle: 'Module 1: Encryption & Site-to-Site IPsec Tunnels',
    moduleDescription: 'Master confidential data transport over public networks using IPsec Security Associations.',
  },
  {
    code: 'NET-403',
    slug: 'net-403-bgp-wan',
    order: 15,
    title: 'BGP & Enterprise WAN Architecture',
    tagline: 'Master Border Gateway Protocol (eBGP/iBGP), Autonomous Systems, and path vector routing.',
    category: 'Advanced',
    description: 'Study inter-domain routing using Border Gateway Protocol (BGP), Autonomous System Numbers (ASN), eBGP peering, and path vector metrics.',
    level: CourseLevel.ADVANCED,
    icon: 'Cloud',
    estimatedHours: 8,
    prerequisitesJson: ['NET-304'],
    moduleTitle: 'Module 1: Autonomous Systems & BGP Routing',
    moduleDescription: 'Understand how global Internet Service Providers exchange IPv4 prefix routes using BGP.',
  },
  {
    code: 'NET-404',
    slug: 'net-404-packet-analysis',
    order: 16,
    title: 'Packet Capture Analysis & Advanced Troubleshooting',
    tagline: 'Master Wireshark PCAP inspection, TCP stream reconstruction, and systematic incident resolution.',
    category: 'Advanced',
    description: 'Inspect raw packet captures in Wireshark, analyze TCP retransmissions, evaluate ICMP error codes, and execute advanced network troubleshooting.',
    level: CourseLevel.ADVANCED,
    icon: 'Search',
    estimatedHours: 8,
    prerequisitesJson: ['NET-204', 'NET-304'],
    moduleTitle: 'Module 1: Wireshark PCAP Inspection & Systematic Troubleshooting',
    moduleDescription: 'Master packet analyzer filters, TCP handshake tracing, and incident troubleshooting workflows.',
  },
];
