'use client';

import React, { useState } from 'react';
import {
  Sparkles,
  Activity,
  Layers,
  CheckCircle2,
  RotateCcw,
  Bot,
} from 'lucide-react';
import { Button } from '@/components/ui/Button';
import {
  SubnetAutoGenesisEngine,
  SubnetGenesisState,
} from '@/lib/subnetAutoGenesisEngine';
import { SoundFx } from '@/lib/soundFx';

export const SubnetAutoGenesisStudio: React.FC = () => {
  const [state, setState] = useState<SubnetGenesisState>(() =>
    SubnetAutoGenesisEngine.getInitialState()
  );
  const [isSynthesizing, setIsSynthesizing] = useState<boolean>(false);
  const [genesisLog, setGenesisLog] = useState<string | null>(null);

  const handleSynthesizeSubnet = () => {
    setIsSynthesizing(true);
    SoundFx.playPacketDispatch();

    setTimeout(() => {
      setState((prev) => ({
        ...prev,
        totalSubnetsAutoGenerated: prev.totalSubnetsAutoGenerated + 1,
        subnets: [
          ...prev.subnets,
          {
            vniId: 10482,
            subnetCidrIpv6: '2001:db8:1000:3::/64',
            subnetCidrIpv4: '10.240.3.0/24',
            securityZone: 'AUTONOMOUS-ROBOTICS-CORE',
            ebpfPolicyRuleCount: 112,
            canaryLatencyMs: 0.35,
            status: 'ACTIVE_PROVISIONED',
          },
        ],
      }));
      setGenesisLog(
        '🤖 AI Sovereign Agent synthesized new subnet VNI 10482 in 1.4s! Zero-touch IPv6 /64 prefix allocated, 112 eBPF egress rules compiled, and Canary probe verified with 0.35 ms latency.'
      );
      setIsSynthesizing(false);
      SoundFx.playSuccessChime();
    }, 500);
  };

  const handleReset = () => {
    SoundFx.playTerminalKeyPress();
    setState(SubnetAutoGenesisEngine.getInitialState());
    setGenesisLog(null);
  };

  return (
    <div className="w-full rounded-3xl bg-[#090b10] border border-[#202538] shadow-2xl overflow-hidden flex flex-col">
      {/* Header */}
      <div className="px-6 py-4 bg-[#10131d] border-b border-[#202538] flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-[#00f0ff]">
            <Bot className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-mono text-[#00f0ff] font-bold uppercase tracking-wider">
                Version 9.6 Subnet Auto-Genesis
              </span>
              <span className="px-2 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-[10px] font-mono font-bold">
                Zero-Touch IPAM • eBPF Synthesis
              </span>
            </div>
            <h2 className="text-lg font-bold text-white tracking-tight">
              AI Sovereign Autonomous Subnet Auto-Genesis & EVPN Provisioning
            </h2>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {!isSynthesizing ? (
            <Button
              variant="primary"
              size="sm"
              onClick={handleSynthesizeSubnet}
              leftIcon={<Sparkles className="w-3.5 h-3.5" />}
            >
              Synthesize New Subnet (AI Auto-Genesis)
            </Button>
          ) : (
            <Button variant="outline" size="sm" disabled>
              Synthesizing EVPN & eBPF...
            </Button>
          )}
          <Button variant="ghost" size="sm" onClick={handleReset} leftIcon={<RotateCcw className="w-3.5 h-3.5" />}>
            Reset
          </Button>
        </div>
      </div>

      {/* Main Grid: Synthesized Subnets (Left) & AI Genesis Telemetry (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 divide-y lg:divide-y-0 lg:divide-x divide-[#202538]">
        {/* Left 7 Cols: Auto-Generated Subnets */}
        <div className="lg:col-span-7 p-6 flex flex-col gap-4 bg-[#0c0e17]">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono font-bold text-zinc-300 uppercase tracking-wider flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-[#00f0ff]" /> Autonomous Subnet Fabrics
            </span>
            <span className="text-[10px] font-mono text-cyan-400 bg-cyan-950/40 px-2 py-0.5 rounded border border-cyan-500/30">
              Total Generated: {state.totalSubnetsAutoGenerated}
            </span>
          </div>

          <div className="space-y-3">
            {state.subnets.map((s) => (
              <div
                key={s.vniId}
                className="p-3.5 rounded-2xl bg-[#121522] border border-[#262c42] flex flex-col gap-1.5"
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-white font-mono">VNI {s.vniId} • {s.securityZone}</span>
                  <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-emerald-950/60 text-emerald-300 border border-emerald-500/30 font-bold">
                    {s.status}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-1 text-[10px] font-mono text-cyan-300">
                  <div>IPv4: {s.subnetCidrIpv4}</div>
                  <div>IPv6: {s.subnetCidrIpv6}</div>
                </div>

                <div className="grid grid-cols-2 gap-2 text-[10px] font-mono text-zinc-400 mt-1">
                  <div>eBPF Rules: <span className="text-white font-bold">{s.ebpfPolicyRuleCount} rules</span></div>
                  <div>Canary Probe: <span className="text-emerald-400 font-bold">{s.canaryLatencyMs} ms</span></div>
                </div>
              </div>
            ))}
          </div>

          {genesisLog && (
            <div className="p-3.5 rounded-2xl bg-cyan-950/30 border border-cyan-500/30 text-xs font-mono text-cyan-200 leading-relaxed animate-in fade-in">
              {genesisLog}
            </div>
          )}
        </div>

        {/* Right 5 Cols: AI Orchestration Mechanics */}
        <div className="lg:col-span-5 p-5 bg-[#090b10] flex flex-col gap-4">
          <div className="flex items-center justify-between pb-2 border-b border-[#202538]">
            <span className="text-xs font-mono font-bold text-zinc-300 uppercase tracking-wider flex items-center gap-1.5">
              <Activity className="w-4 h-4 text-cyan-400" /> Genesis Engine Metrics
            </span>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 rounded-2xl bg-[#121522] border border-[#262c42] flex flex-col">
              <span className="text-[10px] font-mono text-zinc-400 uppercase">Genesis Time</span>
              <span className="text-lg font-bold text-emerald-400 font-mono mt-1">{state.genesisTimeSec}s</span>
              <span className="text-[9px] font-mono text-zinc-500 mt-1">Sub-2s synthesis</span>
            </div>

            <div className="p-3 rounded-2xl bg-[#121522] border border-[#262c42] flex flex-col">
              <span className="text-[10px] font-mono text-zinc-400 uppercase">Human Touches</span>
              <span className="text-lg font-bold text-cyan-400 font-mono mt-1">0 Touches</span>
              <span className="text-[9px] font-mono text-zinc-500 mt-1">100% autonomous</span>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-[#10131d] border border-[#202538] space-y-1.5 text-[11px] font-mono text-zinc-400">
            <div className="text-white font-bold flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400" /> Subnet Auto-Genesis Capabilities
            </div>
            <div>• Inspects incoming container / microservice definitions to determine security requirements</div>
            <div>• Synthesizes zero-trust eBPF firewalls and EVPN route-targets without human review</div>
            <div>• Executes canary ping and health checks before routing production traffic</div>
          </div>
        </div>
      </div>
    </div>
  );
};
